meta_product_name: ".done"
meta_title: ".done - Divorcer c'est compliqué. Constituez votre dossier et trouvez votre avocat en quelques clics."
meta_description: "Répondez à des questions simples, rassemblez vos documents, .done génère un dossier sur-mesure en quelques clics. Simple et rapide, trouvez votre avocat et transmettez lui directement votre dossier complet."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
