meta_product_name: ".done"
meta_title: ".done - Vous êtes prêt à divorcer? On vous aide à vous lancer."
meta_description: "Répondez à des questions simples, rassemblez vos documents, .done génère un dossier sur-mesure en quelques clics. Simple et rapide, trouvez votre avocat et transmettez lui directement votre dossier complet."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
